package scanner;
public enum TokenType {

	//Keywords
		PROGRAM,WHILE,IF,INTEGER,DIV,MOD,OR,AND,DO,ELSE,THEN,FUNCTION,VAR,READ,BEGIN,END,
    	OF,REAL,PROCEDURE,WRITE,ARRAY,NOT,RETURN,
		
	//SYMBOLS
		SEMICOLON,COMMA,COLON,PERIOD,LEFTBRACKET,RIGHTBRACKET,LEFTPARENTHESES,
		RIGHTPARENTHESES,PLUS,MINUS,EQUALS,LESS_THAN,LESS_THAN_OR_EQUAL,GREATER_THAN,
		GREATER_THAN_OR_EQUAL,ASTERISK,SLASH,ASSIGN,GUILLEMENTS,
		
	//Identifiers
		ID, NUMBER,ILLEGAL
		
}